MultiShop/Areas/MultiShopAdmin/ViewModels/Size/CreateSizeVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MultiShopAdmin.ViewModels
{
    public class CreateSizeVM
    {
        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(25, ErrorMessage = "It should not exceed 25 characters")]
        public string Name { get; set; }
    }
}

MultiShop/Areas/MultiShopAdmin/ViewModels/Size/UpdateSizeVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MultiShopAdmin.ViewModels
{
    public class UpdateSizeVM
    {
        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(25, ErrorMessage = "It should not exceed 25 characters")]
        public string Name { get; set; }
    }
}

MultiShop/Models/Size.cs
using MultiShop.Models.Common;

namespace MultiShop.Models
{
    public class Size : BaseNameEntity
    {
        public ICollection<ProductSize>? ProductSizes { get; set; }
    }
}

MultiShop/ViewModels/Size/IncludeSizeVM.cs
namespace MultiShop.ViewModels
{
    public class IncludeSizeVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
    }
}

MultiShop/ViewModels/Size/SizeVM.cs
using NuGet.Protocol.Core.Types;

namespace MultiShop.ViewModels
{
    public class SizeVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<IncludeProductVM> Products { get; set; }
    }
}

MultiShop/Areas/MultiShopAdmin/Controllers/SizeController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiShop.Areas.MultiShopAdmin.ViewModels;
using MultiShop.DAL;
using MultiShop.Models;
using MultiShop.Utilities.Exceptions;
using MultiShop.ViewModels;

namespace MultiShop.Areas.MultiShopAdmin.Controllers
{
    [Area("MultiShopAdmin")]
    [Authorize(Roles = "Admin,Moderator")]
    [AutoValidateAntiforgeryToken]
    public class SizeController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;

        public SizeController(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(int page)
        {
            if (page < 0) throw new WrongRequestException("The request sent does not exist");
            double count = await _context.Sizes.CountAsync();
            ICollection<Size> sizes = await _context.Sizes.Skip(page * 4).Take(4).Include(c => c.ProductSizes).ToListAsync();
            ICollection<SizeVM> vMs = _mapper.Map<ICollection<SizeVM>>(sizes);

            PaginationVM<SizeVM> paginationVM = new PaginationVM<SizeVM>
            {
                CurrentPage = page + 1,
                TotalPage = Math.Ceiling(count / 4),
                Items = vMs
            };
            if (paginationVM.TotalPage < page) throw new NotFoundException("Your request was not found");

            return View(paginationVM);
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSizeVM create)
        {
            if (!ModelState.IsValid)
            {
                return View(create);
            }

            bool result = await _context.Sizes.AnyAsync(c => c.Name.ToLower().Trim() == create.Name.ToLower().Trim());

            if (result)
            {
                ModelState.AddModelError("Color.Name", "A Color with this name already exists");
                return View(create);
            }
            Size size = _mapper.Map<Size>(create);

            await _context.Sizes.AddAsync(size);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Size size = await _context.Sizes.FirstOrDefaultAsync(c => c.Id == id);

            if (size == null) throw new NotFoundException("Your request was not found");
            UpdateSizeVM update = _mapper.Map<UpdateSizeVM>(size);

            return View(update);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateSizeVM update)
        {
            if (!ModelState.IsValid) return View();

            Size existed = await _context.Sizes.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) throw new NotFoundException("Your request was not found");

            bool result = await _context.Sizes.AnyAsync(c => c.Name.ToLower().Trim() == update.Name.ToLower().Trim() && c.Id != id);

            if (result)
            {
                ModelState.AddModelError("Name", "A Size is available");
                return View();
            }

            _mapper.Map(update, existed);
            _context.Sizes.Update(existed);

            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Size existed = await _context.Sizes.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) throw new NotFoundException("Your request was not found");
            _context.Sizes.Remove(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> More(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Size size = await _context.Sizes
                .Include(p => p.ProductSizes)
                .ThenInclude(p => p.Product).ThenInclude(p => p.ProductImages)
                .FirstOrDefaultAsync(c => c.Id == id);
            if (size == null) throw new NotFoundException("Your request was not found");
            SizeVM vM = _mapper.Map<SizeVM>(size);  

            return View(vM);
        }
    }
}

MultiShop/Areas/MultiShopAdmin/Views/Size/Create.cshtml
@model CreateSizeVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Size</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Size Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Size" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

MultiShop/Areas/MultiShopAdmin/Views/Size/Index.cshtml
@model PaginationVM<SizeVM>
@{
    int count = (Model.CurrentPage - 1) * 4;
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Sizes table</h4>
            <a asp-controller="Size" asp-action="Create" class="btn btn-warning fw-bold fs-6 text-white">Create Size</a>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Settings
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (SizeVM size in Model.Items)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    @size.Name
                                </td>
                                <td>
                                    @size.Products.Count
                                </td>
                                <td>
                                    <a asp-action="Update" asp-controller="Size" asp-route-id="@size.Id" class="btn btn-primary btn-info">
                                        <i class="mdi mdi-pencil text-white"></i>
                                    </a>
                                    @if (User.IsInRole(UserRoles.Admin.ToString()))
                                    {
                                        <a asp-action="Delete" asp-controller="Size" asp-route-id="@size.Id" class="btn btn-danger btn-info">
                                            <i class="mdi mdi-delete text-white"></i>
                                        </a>
                                    }
                                    <a asp-action="More" asp-controller="Size" asp-route-id="@size.Id" class="btn btn-primary">
                                        <i class="mdi mdi-open-in-new text-white"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item @(Model.CurrentPage -1 == 0?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-2)" asp-action="Index" asp-controller="Size">Previous</a></li>
                    @for (int i = 0; i < Model.TotalPage; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage-1?"disabled":"")"><a asp-action="Index" asp-route-page="@(i)" asp-controller="Size" class="page-link">@(i + 1)</a></li>
                    }
                    <li class="page-item @(Model.CurrentPage == Model.TotalPage?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage)" asp-action="Index" asp-controller="Size">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

MultiShop/Areas/MultiShopAdmin/Views/Size/More.cshtml
@model SizeVM

<div class="container">
    <h3 class="fw-bold m-3">@Model.Name Products</h3>
    <h4 class="fw-normal mx-5 my-3">Product Count: @Model.Products.Count</h4>
</div>
<div class="container">
    <div class="row row-cols-4 row-cols-md-3 g-4">
        @foreach (IncludeProductVM product in Model.Products)
        {
            <div class="col">
                <div class="card m-1 bg-primary text-white rounded-3">
                    <img src="~/assets/images/website-images/@product.ProductImages.FirstOrDefault(pi => pi.IsPrimary == true).Url"
                         alt="@product.Name" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title text-white">Name: @product.Name</h5>
                        <p class="card-text">Price: $@product.Price</p>
                        <p class="card-text">SKU: @product.SKU</p>
                        <p class="card-text">Description: @product.Description</p>
                    </div>
                </div>
            </div>
        }
    </div>

</div>
<a class="btn btn-light fw-bold fs-4" asp-action="Index" asp-controller="Size">Back</a>

MultiShop/Areas/MultiShopAdmin/Views/Size/Update.cshtml
@model UpdateSizeVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Size</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Size Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Size" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>