MultiShop/Areas/MultiShopAdmin/ViewModels/Color/CreateColorVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MultiShopAdmin.ViewModels
{
    public class CreateColorVM
    {
        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(25, ErrorMessage = "It should not exceed 25 characters")]
        public string Name { get; set; }
    }
}

MultiShop/Areas/MultiShopAdmin/ViewModels/Color/UpdateColorVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MultiShopAdmin.ViewModels
{
    public class UpdateColorVM
    {
        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(25, ErrorMessage = "It should not exceed 25 characters")]
        public string Name { get; set; }
    }
}

MultiShop/Models/Color.cs
using MultiShop.Models.Common;

namespace MultiShop.Models
{
    public class Color : BaseNameEntity
    {
        public ICollection<ProductColor>? ProductColors { get; set; }
    }
}

MultiShop/ViewModels/Color/ColorVM.cs
namespace MultiShop.ViewModels
{
    public class ColorVM
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<IncludeProductVM> Products { get; set; }
    }
}

MultiShop/ViewModels/Color/IncludeColorVM.cs
namespace MultiShop.ViewModels
{
    public record IncludeColorVM(int Id, string Name);
}

MultiShop/Areas/MultiShopAdmin/Controllers/ColorController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiShop.Areas.MultiShopAdmin.ViewModels;
using MultiShop.DAL;
using MultiShop.Models;
using MultiShop.Utilities.Exceptions;
using MultiShop.ViewModels;

namespace MultiShop.Areas.MultiShopAdmin.Controllers
{
    [Area("MultiShopAdmin")]
    [Authorize(Roles = "Admin,Moderator")]
    [AutoValidateAntiforgeryToken]
    public class ColorController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IMapper _mapper;

        public ColorController(AppDbContext context, IMapper mapper)
        {
            _context = context;
            _mapper = mapper;
        }
        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(int page)
        {
            if (page < 0) throw new WrongRequestException("The request sent does not exist");
            double count = await _context.Colors.CountAsync();
            ICollection<Color> colors = await _context.Colors.Skip(page * 4).Take(4)
                .Include(c => c.ProductColors).ToListAsync();
            ICollection<ColorVM> vMs = _mapper.Map<ICollection<ColorVM>>(colors);

            PaginationVM<ColorVM> paginationVM = new PaginationVM<ColorVM>
            {
                CurrentPage = page + 1,
                TotalPage = Math.Ceiling(count / 4),
                Items = vMs
            };
            if (paginationVM.TotalPage < page) throw new NotFoundException("Your request was not found");

            return View(paginationVM);
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateColorVM create)
        {
            if (!ModelState.IsValid)
            {
                return View(create);
            }

            bool result = await _context.Colors.AnyAsync(c => c.Name.ToLower().Trim() == create.Name.ToLower().Trim());

            if (result)
            {
                ModelState.AddModelError("Name", "A Color with this name already exists");
                return View(create);
            }
            Color color = _mapper.Map<Color>(create);

            await _context.Colors.AddAsync(color);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Color color = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);

            if (color == null) throw new NotFoundException("Your request was not found");
            UpdateColorVM update = _mapper.Map<UpdateColorVM>(color);


            return View(update);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateColorVM update)
        {
            if (!ModelState.IsValid) return View(update);

            Color existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) throw new NotFoundException("Your request was not found");

            bool result = await _context.Colors.AnyAsync(c => c.Name.ToLower().Trim() == update.Name.ToLower().Trim() && c.Id != id);

            if (result)
            {
                ModelState.AddModelError("Name", "A Color is available");
                return View(update);
            }

            _mapper.Map(update, existed);
            _context.Colors.Update(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Color existed = await _context.Colors.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) throw new NotFoundException("Your request was not found");
            _context.Colors.Remove(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> More(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Color color = await _context.Colors
                .Include(p => p.ProductColors)
                .ThenInclude(p => p.Product).ThenInclude(p => p.ProductImages)
                .FirstOrDefaultAsync(c => c.Id == id);
            if (color == null) throw new NotFoundException("Your request was not found");
            ColorVM vM = _mapper.Map<ColorVM>(color);
 
            return View(vM);
        }
    }
}

MultiShop/Areas/MultiShopAdmin/Views/Color/Create.cshtml
@model CreateColorVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Color</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Color Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Color" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

MultiShop/Areas/MultiShopAdmin/Views/Color/Index.cshtml
@model PaginationVM<ColorVM>
@{
    int count = (Model.CurrentPage - 1) * 4;
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Colors table</h4>
            <a asp-controller="Color" asp-action="Create" class="btn btn-warning fw-bold fs-6 text-white">Create Color</a>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Name
                            </th>
                            <th>
                                Settings
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (ColorVM color in Model.Items)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    @color.Name
                                </td>
                                <td>
                                    @color.Products.Count
                                </td>
                                <td>
                                    <a asp-action="Update" asp-controller="Color" asp-route-id="@color.Id" class="btn btn-primary btn-info">
                                        <i class="mdi mdi-pencil text-white"></i>
                                    </a>
                                    @if (User.IsInRole(UserRoles.Admin.ToString()))
                                    {
                                        <a asp-action="Delete" asp-controller="Color" asp-route-id="@color.Id" class="btn btn-danger btn-info">
                                            <i class="mdi mdi-delete text-white"></i>
                                        </a>
                                    }
                                    <a asp-action="More" asp-controller="Color" asp-route-id="@color.Id" class="btn btn-primary">
                                        <i class="mdi mdi-open-in-new text-white"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item @(Model.CurrentPage -1 == 0?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-2)" asp-action="Index" asp-controller="Color">Previous</a></li>
                    @for (int i = 0; i < Model.TotalPage; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage-1?"disabled":"")"><a asp-action="Index" asp-route-page="@(i)" asp-controller="Color" class="page-link">@(i + 1)</a></li>
                    }
                    <li class="page-item @(Model.CurrentPage == Model.TotalPage?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage)" asp-action="Index" asp-controller="Color">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

MultiShop/Areas/MultiShopAdmin/Views/Color/More.cshtml
@model ColorVM

<div class="container">
    <h3 class="fw-bold m-3">@Model.Name Products</h3>
    <h4 class="fw-normal mx-5 my-3">Product Count: @Model.Products.Count</h4>
</div>
<div class="container">
    <div class="row row-cols-4 row-cols-md-3 g-4">
        @foreach (IncludeProductVM product in Model.Products)
        {
            <div class="col">
                <div class="card m-1 bg-primary text-white rounded-3">
                    <img src="~/assets/images/website-images/@product.ProductImages.FirstOrDefault(pi => pi.IsPrimary == true).Url"
                         alt="@product.Name" class="card-img-top">
                    <div class="card-body">
                        <h5 class="card-title text-white">Name: @product.Name</h5>
                        <p class="card-text">Price: $@product.Price</p>
                        <p class="card-text">SKU: @product.SKU</p>
                        <p class="card-text">Description: @product.Description</p>
                    </div>
                </div>
            </div>
        }
    </div>

</div>
<a class="btn btn-light fw-bold fs-4" asp-action="Index" asp-controller="Color">Back</a>

MultiShop/Areas/MultiShopAdmin/Views/Color/Update.cshtml
@model UpdateColorVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Color</h4>
            <form class="forms-sample" method="post">
                <div class="form-group">
                    <label asp-for="Name">Color Name</label>
                    <input asp-for="Name" class="form-control" placeholder="Name">
                    <span asp-validation-for="Name" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Color" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>