MultiShop/Areas/MultiShopAdmin/ViewModels/Slide/CreateSlideVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MultiShopAdmin.ViewModels
{
    public class CreateSlideVM
    {
        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(25, ErrorMessage = "It should not exceed 25 characters")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(150, ErrorMessage = "It should not exceed 150 characters")]
        public string SubTitle { get; set; }

        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(20, ErrorMessage = "It should not exceed 20 characters")]
        public string ButtonText { get; set; }

        [Required(ErrorMessage = "OrderId must be entered mutled")]
        public int OrderId { get; set; }


        [Required(ErrorMessage = "Image must be uploaded")]
        public IFormFile Photo { get; set; }
    }
}

MultiShop/Areas/MultiShopAdmin/ViewModels/Slide/UpdateSlideVM.cs
using System.ComponentModel.DataAnnotations;

namespace MultiShop.Areas.MultiShopAdmin.ViewModels
{
    public class UpdateSlideVM
    {
        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(25, ErrorMessage = "It should not exceed 25 characters")]
        public string Title { get; set; }

        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(150, ErrorMessage = "It should not exceed 150 characters")]
        public string SubTitle { get; set; }

        [Required(ErrorMessage = "Name must be entered mutled")]
        [MaxLength(20, ErrorMessage = "It should not exceed 20 characters")]
        public string ButtonText { get; set; }

        [Required(ErrorMessage = "OrderId must be entered mutled")]
        public int OrderId { get; set; }

        public string ImgUrl { get; set; }

        public IFormFile? Photo { get; set; }
    }
}

MultiShop/Models/Slide.cs
using MultiShop.Models.Common;

namespace MultiShop.Models
{
    public class Slide : BaseEntity
    {
        public string Title { get; set; } = null!;
        public string SubTitle { get; set; } = null!;
        public string ButtonText { get; set; } = "Shop Now";
        public int OrderId { get; set; }
        public string ImgUrl { get; set; } = null!;

    }
}

MultiShop/ViewModels/Slide/SlideVM.cs
namespace MultiShop.ViewModels
{
    public class SlideVM
    {
        public int Id { get; set; }
        public string Title { get; set; }
        public string SubTitle { get; set; }
        public string? ButtonText { get; set; }
        public int OrderId { get; set; }
        public string ImgUrl { get; set; }
    }
}

MultiShop/Areas/MultiShopAdmin/Controllers/SlideController.cs
using AutoMapper;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using Microsoft.EntityFrameworkCore;
using MultiShop.Areas.MultiShopAdmin.ViewModels;
using MultiShop.DAL;
using MultiShop.Models;
using MultiShop.Utilities.Exceptions;
using MultiShop.Utilities.Extendions;
using MultiShop.ViewModels;

namespace MultiShop.Areas.MultiShopAdmin.Controllers
{
    [Area("MultiShopAdmin")]
    [Authorize(Roles = "Admin,Moderator")]
    [AutoValidateAntiforgeryToken]
    public class SlideController : Controller
    {
        private readonly AppDbContext _context;
        private readonly IWebHostEnvironment _env;
        private readonly IMapper _mapper;

        public SlideController(AppDbContext context, IWebHostEnvironment env, IMapper mapper)
        {
            _context = context;
            _env = env;
            _mapper = mapper;
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Index(int page)
        {
            if (page < 0) throw new WrongRequestException("The request sent does not exist");
            double count = await _context.Slides.CountAsync();
            ICollection<Slide> slide = await _context.Slides.Skip(page*4).Take(4).ToListAsync();
            ICollection <SlideVM> vMs = _mapper.Map<ICollection<SlideVM>>(slide);

            PaginationVM<SlideVM> paginationVM = new PaginationVM<SlideVM>
            {
                CurrentPage = page + 1,
                TotalPage = Math.Ceiling(count / 4),
                Items = vMs
            };
            if (paginationVM.TotalPage < page) throw new NotFoundException("Your request was not found");

            return View(paginationVM);
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public IActionResult Create()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> Create(CreateSlideVM create)
        {
            if (!ModelState.IsValid) return View(create);

            if (create.Photo is null)
            {
                ModelState.AddModelError("Photo", "The image must be uploaded");
                return View(create);
            }

            if (!create.Photo.ValidateType())
            {
                ModelState.AddModelError("Photo", "File Not supported");
                return View(create);
            }

            if (!create.Photo.ValidataSize(10))
            {
                ModelState.AddModelError("Photo", "Image should not be larger than 10 mb");
                return View(create);
            }

            Slide slide = _mapper.Map<Slide>(create);
            slide.ImgUrl = await create.Photo.CreateFileAsync(_env.WebRootPath, "img");

            await _context.Slides.AddAsync(slide);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Update(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Slide slide = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);

            if (slide == null) throw new NotFoundException("Your request was not found");

            UpdateSlideVM update = _mapper.Map<UpdateSlideVM>(slide);

            return View(update);
        }

        [HttpPost]
        public async Task<IActionResult> Update(int id, UpdateSlideVM update)
        {
            if (!ModelState.IsValid) return View(update);

            Slide existed = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);
            if (existed == null) throw new NotFoundException("Your request was not found");
            if (update.Photo is not null)
            {

                if (!update.Photo.ValidateType())
                {
                    ModelState.AddModelError("Photo", "File Not supported");
                    return View(existed);
                }

                if (!update.Photo.ValidataSize(10))
                {
                    ModelState.AddModelError("Photo", "Image should not be larger than 10 mb");
                    return View(existed);
                }

                string fileName = await update.Photo.CreateFileAsync(_env.WebRootPath, "img");
                existed.ImgUrl.DeleteFileAsync(_env.WebRootPath, "img");
                existed.ImgUrl = fileName;
                update.ImgUrl = fileName;
            }

            _mapper.Map(update, existed);

            _context.Slides.Update(existed);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> Delete(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");

            Slide existed = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);

            if (existed == null) throw new NotFoundException("Your request was not found");

            existed.ImgUrl.DeleteFileAsync(_env.WebRootPath, "img");

            _context.Slides.Remove(existed);
            await _context.SaveChangesAsync();

            return RedirectToAction(nameof(Index));
        }

        [Authorize(Roles = "Admin,Moderator")]
        [AutoValidateAntiforgeryToken]
        public async Task<IActionResult> More(int id)
        {
            if (id <= 0) throw new WrongRequestException("The request sent does not exist");
            Slide slide = await _context.Slides.FirstOrDefaultAsync(c => c.Id == id);
            if (slide == null) throw new NotFoundException("Your request was not found");
            SlideVM vM = _mapper.Map<SlideVM>(slide);

            return View(vM);
        }
    }
}

MultiShop/Areas/MultiShopAdmin/Views/Slide/Create.cshtml
@model CreateSlideVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Create Slide</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Title">Title</label>
                    <input asp-for="Title" class="form-control" placeholder="Title">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubTitle">Sub-Title Name</label>
                    <input asp-for="SubTitle" class="form-control" placeholder="Sub-Title">
                    <span asp-validation-for="SubTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="OrderId">OrderId</label>
                    <input asp-for="OrderId" class="form-control" placeholder="OrderId">
                    <span asp-validation-for="OrderId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ButtonText">Button Text</label>
                    <input asp-for="ButtonText" class="form-control" placeholder="Button Text">
                    <span asp-validation-for="ButtonText" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="Photo">Image</label>
                    <input asp-for="Photo" class="form-control" placeholder="Image">
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Slide" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>

MultiShop/Areas/MultiShopAdmin/Views/Slide/Index.cshtml
@model PaginationVM<SlideVM>
@{
    int count = (Model.CurrentPage - 1) * 4;
}
<div class="col-lg-12 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Slides table</h4>
            <a asp-controller="Slide" asp-action="Create" class="btn btn-warning fw-bold fs-6 text-white">Create Slide</a>
            <div class="table-responsive pt-3">
                <table class="table table-bordered">
                    <thead>
                        <tr>
                            <th>
                                #
                            </th>
                            <th>
                                Image
                            </th>
                            <th>
                                Title
                            </th>
                            <th>
                                Settings
                            </th>
                        </tr>
                    </thead>
                    <tbody>
                        @foreach (SlideVM slide in Model.Items)
                        {
                            count++;
                            <tr>
                                <td>
                                    @count
                                </td>
                                <td>
                                    <img src="~/img//@slide.ImgUrl">
                                </td>
                                <td>
                                    @slide.Title
                                </td>
                                <td>
                                    <a asp-action="Update" asp-controller="Slide" asp-route-id="@slide.Id" class="btn btn-primary btn-info">
                                        <i class="mdi mdi-pencil text-white"></i>
                                    </a>
                                    @if (User.IsInRole(UserRoles.Admin.ToString()))
                                    {
                                        <a asp-action="Delete" asp-controller="Slide" asp-route-id="@slide.Id" class="btn btn-danger btn-info">
                                            <i class="mdi mdi-delete text-white"></i>
                                        </a>
                                    }
                                    <a asp-action="More" asp-controller="Slide" asp-route-id="@slide.Id" class="btn btn-primary">
                                        <i class="mdi mdi-open-in-new text-white"></i>
                                    </a>
                                </td>
                            </tr>
                        }
                    </tbody>
                </table>
            </div>
            <nav aria-label="Page navigation example">
                <ul class="pagination justify-content-center">
                    <li class="page-item @(Model.CurrentPage -1 == 0?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage-2)" asp-action="Index" asp-controller="Slide">Previous</a></li>
                    @for (int i = 0; i < Model.TotalPage; i++)
                    {
                        <li class="page-item @(i == Model.CurrentPage-1?"disabled":"")"><a asp-action="Index" asp-route-page="@(i)" asp-controller="Slide" class="page-link">@(i + 1)</a></li>
                    }
                    <li class="page-item @(Model.CurrentPage == Model.TotalPage?"disabled":"")"><a class="page-link" asp-route-page="@(Model.CurrentPage)" asp-action="Index" asp-controller="Slide">Next</a></li>
                </ul>
            </nav>
        </div>
    </div>
</div>

MultiShop/Areas/MultiShopAdmin/Views/Slide/More.cshtml
@model SlideVM

<div class="container">
    <div class="card mb-3" style="max-width: 99%;">
        <div class="row g-0">
            <div class="col-md-4">
                <img src="~/img//@Model.ImgUrl" class="img-fluid rounded-start w-75" alt="@Model.Title">
            </div>
            <div class="col-md-8">
                <div class="card-body">
                    <h5 class="card-title">Title: @Model.Title</h5>
                    <p class="card-text">Sub-Title: @Model.SubTitle</p>
                    <p class="card-text">Button Text: @Model.ButtonText</p>
                    <p class="card-text">Orederİd Text: @Model.OrderId</p>
                </div>
            </div>
        </div>
    </div>
</div>
<a class="btn btn-light fw-bold fs-4" asp-action="Index" asp-controller="Slide">Back</a>

MultiShop/Areas/MultiShopAdmin/Views/Slide/Update.cshtml
@model UpdateSlideVM

<div class="col-md-6 grid-margin stretch-card">
    <div class="card">
        <div class="card-body">
            <h4 class="card-title">Update Slide</h4>
            <form class="forms-sample" method="post" enctype="multipart/form-data">
                <div class="form-group">
                    <label asp-for="Title">Title Name</label>
                    <input asp-for="Title" class="form-control" placeholder="Title">
                    <span asp-validation-for="Title" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="SubTitle">Sub-Title Name</label>
                    <input asp-for="SubTitle" class="form-control" placeholder="Sub-Title">
                    <span asp-validation-for="SubTitle" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="ButtonText">Button Text</label>
                    <input asp-for="ButtonText" class="form-control" placeholder="Button Text">
                    <span asp-validation-for="ButtonText" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <label asp-for="OrderId">OrderId</label>
                    <input asp-for="OrderId" class="form-control" placeholder="OrderId">
                    <span asp-validation-for="OrderId" class="text-danger"></span>
                </div>
                <div class="form-group">
                    <img src="~/img//@Model.ImgUrl" width="25%" />
                    <input asp-for="ImgUrl" type="hidden" class="form-control">
                </div>
                <div class="form-group">
                    <label asp-for="Photo">Image</label>
                    <input asp-for="Photo" class="form-control" placeholder="Photo">
                    <span asp-validation-for="Photo" class="text-danger"></span>
                </div>
                <button type="submit" class="btn btn-primary me-2">Submit</button>
                <a asp-action="Index" asp-controller="Slide" class="btn btn-light">Cancel</a>
            </form>
        </div>
    </div>
</div>